sudo: false
language: node_js
services:
  - mongodb
before_install:
  - npm update -g npm
before_script:
  - npm install -g gulp
  - mysql -e 'create database code_friends;'
  - mysql -e 'create database code_friends_test;'
node_js:
  - '0.10'
notifications:
  email: false