db:
  image: tutum/mysql:5.5
  ports:
   - "3306:3306"
  environment:
    MYSQL_PASS: "6gdP7R3adDYNehj"
server:
  build: .
  ports:
   - "80:80"
   - "9000:9000"
   - "9001:9001"
  expose:
   - "80"
   - "9000"
   - "9001"
  links:
   - "db:db"
  volumes:
   - ./config:/app/config
   - ./server:/app/server
   - ./client:/app/client
  environment:
    NODE_ENV: dev
    PORT: 80