db:
  image: tutum/mysql:5.5
  ports:
   - "3306:3306"
  environment:
    MYSQL_PASS: "6gdP7R3adDYNehj"
server:
  build: .
  ports:
   - "8005:80"
   - "8001:8001"
   - "8007:8007"
  expose:
   - "80"
   - "8001"
   - "8007"
  links:
   - "db:db"
  environment:
    NODE_ENV: staging
    PORT: 80